version: 0.2

phases:
  install:
    commands:
      - apt update
      - apt-get install openjdk-11-jdk -y
      - java -version
      - wget https://services.gradle.org/distributions/gradle-6.6-bin.zip -P /tmp
      - unzip -d /opt/gradle /tmp/gradle-*.zip
      - ls /opt/gradle/gradle-6.6
      - export GRADLE_HOME=/opt/gradle/gradle-6.6
      - export PATH=${GRADLE_HOME}/bin:${PATH}
      - gradle -v

  build:
    commands:
      - cd location-crud
      - gradle build
      - cd ..
      - cd product-crud
      - gradle build
      - cd ..
      - cd balance-crud
      - gradle build
      - cd ..
  artifacts:
    files:
      - location-crud/build/libs/location-crud-0.0.1-SNAPSHOT.jar
    name: location-crud
    secondary-artifacts:
      product-crud:
        files:
          - procut-crud/build/libs/product-crud-0.0.1-SNAPSHOT.jar
        name: product-crud
      balance-crud:
        files:
          - balance-crud/build/libs/balance-crud-0.0.1-SNAPSHOT.jar
        name: balance-crud