version: 0.2

phases:
  install:
    commands:
      - apt update
      - apt-get install openjdk-11-jdk -y
      - wget https://services.gradle.org/distributions/gradle-6.6-bin.zip -P /tmp
      - unzip -d /opt/gradle /tmp/gradle-*.zip
      - ls /opt/gradle/gradle-6.6
      - export GRADLE_HOME=/opt/gradle/gradle-6.6
      - export PATH=${GRADLE_HOME}/bin:${PATH}

  build:
    commands:
      - cd location-crud
      - gradle build
      - cd ..
      - cd product-crud
      - gradle build
      - cd ..
      - cd balance-crud
      - gradle build
      - cd ..
artifacts:
  secondary-artifacts:
    location_crud:
      files:
        - location-crud/build/libs/location-crud-0.0.1-SNAPSHOT.jar
        - location-crud/appspec.yml
        - location-crud/scripts/start_server.sh
        - location-crud/scripts/stop_server.sh
        - location-crud/scripts/clean.sh
      discard-paths: yes
      name: location_crud
    product_crud:
      files:
        - product-crud/build/libs/product-crud-0.0.1-SNAPSHOT.jar
        - product-crud/appspec.yml
        - product-crud/scripts/start_server.sh
        - product-crud/scripts/stop_server.sh
        - product-crud/scripts/clean.sh
      discard-paths: yes
      name: product_crud
    balance_crud:
      files:
        - balance-crud/build/libs/balance-crud-0.0.1-SNAPSHOT.jar
        - balance-crud/appspec.yml
        - balance-crud/scripts/start_server.sh
        - balance-crud/scripts/stop_server.sh
        - balance-crud/scripts/clean.sh
      discard-paths: yes
      name: balance_crud