insert into department (id, dept_name) values (1, 'Kids');
insert into department (id, dept_name) values (2, 'Tools');
insert into department (id, dept_name) values (3, 'Clothing');
insert into department (id, dept_name) values (4, 'Games');
insert into department (id, dept_name) values (5, 'Health');
insert into department (id, dept_name) values (7, 'Jewelery');
insert into department (id, dept_name) values (8, 'Kids');
insert into department (id, dept_name) values (9, 'Toys');
insert into department (id, dept_name) values (10, 'Beauty');
