version: 0.0
os: linux
files:
  - source: /
    destination: /var/crud/
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: clean.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root