version: 0.0
os: linux
files:
  - source: balance-crud-0.0.1-SNAPSHOT.jar
    destination: /var/crud/
hooks:
  ApplicationStop:
    -location: scripts/stop_server.sh
     timeout: 300
     runas: root
  BeforeInstall:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root