spring:
  application:
    name: balance-crud
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.cpi0qs5lqerp.us-east-1.rds.amazonaws.com:3306/ProductAvailability
    username: admin
    password: password
    driverClassName: com.mysql.jdbc.Driver
  memcached.cache:
    servers: product-availability.qwn7sl.0001.use1.cache.amazonaws.com:11211
    provider: aws
    experiation: 86400
server:
  port: 8083